version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    networks:
      - chat-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - REACT_APP_SOCKET_URL=http://backend:5000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chat-net

networks:
  chat-net:
