version: '3'
services:
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "8081:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: always
